### ISSUE TITLE
build fails on Ubuntu 12.04 Precise

### ISSUE THREAD

**Issue by mikegogulski** [ironport/shrapnel#48]
Sam: email an SSH key to mike@gogulski.com if you'd like an account to test in my environment.

log:

syadasti@charlie:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.3 LTS"
syadasti@charlie:~$ uname -a
Linux charlie 3.5.0-40-generic #62~precise1-Ubuntu SMP Fri Aug 23 17:38:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
syadasti@charlie:~$ python --version
Python 2.7.3
syadasti@charlie:~$ cython --version
Cython version 0.15.1
syadasti@charlie:~$ git clone https://github.com/ironport/shrapnel.git
Cloning into 'shrapnel'...
remote: Counting objects: 2083, done.
remote: Compressing objects: 100% (876/876), done.
remote: Total 2083 (delta 1214), reused 2032 (delta 1175)
Receiving objects: 100% (2083/2083), 1.01 MiB | 294 KiB/s, done.
Resolving deltas: 100% (1214/1214), done.
syadasti@charlie:~$ cd shrapnel
syadasti@charlie:~/shrapnel$ python setup.py build
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.26.tar.gz
Extracting in /tmp/tmpsDqnRw
Now working in /tmp/tmpsDqnRw/distribute-0.6.26
Building a Distribute egg in /home/syadasti/shrapnel
warning: no files found matching 'Makefile' under directory 'docs'
warning: no files found matching 'indexsidebar.html' under directory 'docs'
/home/syadasti/shrapnel/distribute-0.6.26-py2.7.egg
test/build/test_lio.c:8:23: fatal error: sys/event.h: No such file or directory
compilation terminated.
detected NPN-capable OpenSSL
/usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'cython_compile_time_env'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'pyrex_compile_time_env'
  warnings.warn(msg)
running build
running build_py
file backdoor.py (for module backdoor) not found
file coro_process.py (for module coro_process) not found
file coro_unittest.py (for module coro_unittest) not found
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/coro
copying coro/**init**.py -> build/lib.linux-x86_64-2.7/coro
copying coro/read_stream.py -> build/lib.linux-x86_64-2.7/coro
copying coro/backdoor.py -> build/lib.linux-x86_64-2.7/coro
copying coro/print_profile.py -> build/lib.linux-x86_64-2.7/coro
copying coro/optional.py -> build/lib.linux-x86_64-2.7/coro
copying coro/frontdoor.py -> build/lib.linux-x86_64-2.7/coro
copying coro/signal_handler.py -> build/lib.linux-x86_64-2.7/coro
copying coro/profiler.py -> build/lib.linux-x86_64-2.7/coro
copying coro/tb.py -> build/lib.linux-x86_64-2.7/coro
creating build/lib.linux-x86_64-2.7/coro/http
copying coro/http/websocket.py -> build/lib.linux-x86_64-2.7/coro/http
copying coro/http/handlers.py -> build/lib.linux-x86_64-2.7/coro/http
copying coro/http/http_date.py -> build/lib.linux-x86_64-2.7/coro/http
copying coro/http/client.py -> build/lib.linux-x86_64-2.7/coro/http
copying coro/http/spdy.py -> build/lib.linux-x86_64-2.7/coro/http
copying coro/http/json_rpc.py -> build/lib.linux-x86_64-2.7/coro/http
copying coro/http/session_handler.py -> build/lib.linux-x86_64-2.7/coro/http
copying coro/http/server.py -> build/lib.linux-x86_64-2.7/coro/http
copying coro/http/**init**.py -> build/lib.linux-x86_64-2.7/coro/http
copying coro/http/protocol.py -> build/lib.linux-x86_64-2.7/coro/http
creating build/lib.linux-x86_64-2.7/coro/ssl
copying coro/ssl/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssl
creating build/lib.linux-x86_64-2.7/coro/emulation
copying coro/emulation/thread.py -> build/lib.linux-x86_64-2.7/coro/emulation
copying coro/emulation/threading.py -> build/lib.linux-x86_64-2.7/coro/emulation
copying coro/emulation/socket.py -> build/lib.linux-x86_64-2.7/coro/emulation
copying coro/emulation/**init**.py -> build/lib.linux-x86_64-2.7/coro/emulation
creating build/lib.linux-x86_64-2.7/coro/dns
copying coro/dns/reply.py -> build/lib.linux-x86_64-2.7/coro/dns
copying coro/dns/cache.py -> build/lib.linux-x86_64-2.7/coro/dns
copying coro/dns/stub_resolver.py -> build/lib.linux-x86_64-2.7/coro/dns
copying coro/dns/**init**.py -> build/lib.linux-x86_64-2.7/coro/dns
copying coro/dns/exceptions.py -> build/lib.linux-x86_64-2.7/coro/dns
creating build/lib.linux-x86_64-2.7/coro/clocks
copying coro/clocks/**init**.py -> build/lib.linux-x86_64-2.7/coro/clocks
creating build/lib.linux-x86_64-2.7/coro/asn1
copying coro/asn1/**init**.py -> build/lib.linux-x86_64-2.7/coro/asn1
creating build/lib.linux-x86_64-2.7/coro/ssh
copying coro/ssh/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh
creating build/lib.linux-x86_64-2.7/coro/db
copying coro/db/**init**.py -> build/lib.linux-x86_64-2.7/coro/db
creating build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/static_key_storage.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/openssh_authorized_keys.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/key_storage.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/dss.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/remote_host.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/public_private_key.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/rsa.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/openssh_key_storage.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/rebuild.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/openssh_key_formats.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/openssh_known_hosts.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
copying coro/ssh/keys/ber.py -> build/lib.linux-x86_64-2.7/coro/ssh/keys
creating build/lib.linux-x86_64-2.7/coro/ssh/transport
copying coro/ssh/transport/client.py -> build/lib.linux-x86_64-2.7/coro/ssh/transport
copying coro/ssh/transport/constants.py -> build/lib.linux-x86_64-2.7/coro/ssh/transport
copying coro/ssh/transport/transport.py -> build/lib.linux-x86_64-2.7/coro/ssh/transport
copying coro/ssh/transport/server.py -> build/lib.linux-x86_64-2.7/coro/ssh/transport
copying coro/ssh/transport/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh/transport
creating build/lib.linux-x86_64-2.7/coro/ssh/l4_transport
copying coro/ssh/l4_transport/coro_socket_transport.py -> build/lib.linux-x86_64-2.7/coro/ssh/l4_transport
copying coro/ssh/l4_transport/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh/l4_transport
creating build/lib.linux-x86_64-2.7/coro/ssh/scp
copying coro/ssh/scp/client.py -> build/lib.linux-x86_64-2.7/coro/ssh/scp
copying coro/ssh/scp/core.py -> build/lib.linux-x86_64-2.7/coro/ssh/scp
copying coro/ssh/scp/cli.py -> build/lib.linux-x86_64-2.7/coro/ssh/scp
copying coro/ssh/scp/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh/scp
creating build/lib.linux-x86_64-2.7/coro/ssh/auth
copying coro/ssh/auth/userauth.py -> build/lib.linux-x86_64-2.7/coro/ssh/auth
copying coro/ssh/auth/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh/auth
creating build/lib.linux-x86_64-2.7/coro/ssh/wrapper
copying coro/ssh/wrapper/coro_interactive_ssh_wrapper.py -> build/lib.linux-x86_64-2.7/coro/ssh/wrapper
copying coro/ssh/wrapper/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh/wrapper
creating build/lib.linux-x86_64-2.7/coro/ssh/connection
copying coro/ssh/connection/interactive_session.py -> build/lib.linux-x86_64-2.7/coro/ssh/connection
copying coro/ssh/connection/constants.py -> build/lib.linux-x86_64-2.7/coro/ssh/connection
copying coro/ssh/connection/tty_modes.py -> build/lib.linux-x86_64-2.7/coro/ssh/connection
copying coro/ssh/connection/data_buffer.py -> build/lib.linux-x86_64-2.7/coro/ssh/connection
copying coro/ssh/connection/channel.py -> build/lib.linux-x86_64-2.7/coro/ssh/connection
copying coro/ssh/connection/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh/connection
copying coro/ssh/connection/connect.py -> build/lib.linux-x86_64-2.7/coro/ssh/connection
creating build/lib.linux-x86_64-2.7/coro/ssh/key_exchange
copying coro/ssh/key_exchange/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh/key_exchange
copying coro/ssh/key_exchange/diffie_hellman.py -> build/lib.linux-x86_64-2.7/coro/ssh/key_exchange
creating build/lib.linux-x86_64-2.7/coro/ssh/compression
copying coro/ssh/compression/none.py -> build/lib.linux-x86_64-2.7/coro/ssh/compression
copying coro/ssh/compression/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh/compression
creating build/lib.linux-x86_64-2.7/coro/ssh/util
copying coro/ssh/util/mpint.py -> build/lib.linux-x86_64-2.7/coro/ssh/util
copying coro/ssh/util/debug.py -> build/lib.linux-x86_64-2.7/coro/ssh/util
copying coro/ssh/util/password.py -> build/lib.linux-x86_64-2.7/coro/ssh/util
copying coro/ssh/util/packet.py -> build/lib.linux-x86_64-2.7/coro/ssh/util
copying coro/ssh/util/random.py -> build/lib.linux-x86_64-2.7/coro/ssh/util
copying coro/ssh/util/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh/util
creating build/lib.linux-x86_64-2.7/coro/ssh/mac
copying coro/ssh/mac/hmac.py -> build/lib.linux-x86_64-2.7/coro/ssh/mac
copying coro/ssh/mac/hmac_sha1.py -> build/lib.linux-x86_64-2.7/coro/ssh/mac
copying coro/ssh/mac/hmac_md5.py -> build/lib.linux-x86_64-2.7/coro/ssh/mac
copying coro/ssh/mac/none.py -> build/lib.linux-x86_64-2.7/coro/ssh/mac
copying coro/ssh/mac/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh/mac
creating build/lib.linux-x86_64-2.7/coro/ssh/cipher
copying coro/ssh/cipher/none.py -> build/lib.linux-x86_64-2.7/coro/ssh/cipher
copying coro/ssh/cipher/blowfish_cbc.py -> build/lib.linux-x86_64-2.7/coro/ssh/cipher
copying coro/ssh/cipher/**init**.py -> build/lib.linux-x86_64-2.7/coro/ssh/cipher
copying coro/ssh/cipher/des3_cbc.py -> build/lib.linux-x86_64-2.7/coro/ssh/cipher
creating build/lib.linux-x86_64-2.7/coro/db/postgres
copying coro/db/postgres/postgres.py -> build/lib.linux-x86_64-2.7/coro/db/postgres
copying coro/db/postgres/**init**.py -> build/lib.linux-x86_64-2.7/coro/db/postgres
file backdoor.py (for module backdoor) not found
file coro_process.py (for module coro_process) not found
file coro_unittest.py (for module coro_unittest) not found
running build_ext
cythoning coro/event_queue.pyx to coro/event_queue.cpp
building 'coro.event_queue' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/coro
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c coro/event_queue.cpp -o build/temp.linux-x86_64-2.7/coro/event_queue.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/coro/event_queue.o -o build/lib.linux-x86_64-2.7/coro/event_queue.so
cythoning coro/_coro.pyx to coro/_coro.c
## Error compiling Cython file:

...
    cdef _die (self)
    cdef __interrupt (self, the_exception)
    cdef int try_selfish (self)
# choose a library for stack compression

IF COMPILE_LZ4:
##              ^

coro/_coro.pxd:126:14: Compile-time name 'COMPILE_LZ4' not defined
## Error compiling Cython file:

...
    cdef int try_selfish (self)
# choose a library for stack compression

IF COMPILE_LZ4:
    include "zstack_lz4.pxd"
ELIF COMPILE_LZO:
##                ^

coro/_coro.pxd:128:16: Compile-time name 'COMPILE_LZO' not defined
## Error compiling Cython file:

...

```
def __dealloc__ (self):
    global live_coros
    live_coros = live_coros - 1
    if self.stack_copy != NULL:
        IF CORO_DEBUG:
                    ^
```

---

coro/_coro.pyx:241:25: Compile-time name 'CORO_DEBUG' not defined
## Error compiling Cython file:

...
              `force` was set to False).
        :raises ScheduleError: Attempted to raise an exception on the currently
              running coro.
        :raises NotStartedError: The coroutine has not started, yet.
        """
        IF CORO_DEBUG:
##                     ^

coro/_coro.pyx:557:21: Compile-time name 'CORO_DEBUG' not defined
## Error compiling Cython file:

...

class WakeUp (Exception):
    """A convenience exception used to wake up a sleeping thread."""
# choose a library for stack compression

IF COMPILE_LZ4:
##              ^

coro/_coro.pyx:865:14: Compile-time name 'COMPILE_LZ4' not defined
## Error compiling Cython file:

...
    """A convenience exception used to wake up a sleeping thread."""
# choose a library for stack compression

IF COMPILE_LZ4:
    include "zstack_lz4.pyx"
ELIF COMPILE_LZO:
##                ^

coro/_coro.pyx:867:16: Compile-time name 'COMPILE_LZO' not defined
## Error compiling Cython file:

...
                self._last.compressed = False
            #2) get some storage
            if self._last.stack_size != size:
                # XXX: more heuristics to avoid malloc
                if self._last.stack_copy:
                    IF CORO_DEBUG:
##                                 ^

coro/_coro.pyx:939:33: Compile-time name 'CORO_DEBUG' not defined
## Error compiling Cython file:

...
        :raises TimeoutError: The function did not return within the specified
              timeout.
        """
        cdef timebomb tb
        cdef event e
        IF CORO_DEBUG:
##                     ^

coro/_coro.pyx:1081:21: Compile-time name 'CORO_DEBUG' not defined
## Error compiling Cython file:

...
        """Sleep until a specific point in time.

```
    :param when: The TSC value when you want the coroutine to wake up.
    """
    cdef event e
    IF CORO_DEBUG:
                ^
```

---

coro/_coro.pyx:1113:21: Compile-time name 'CORO_DEBUG' not defined
## Error compiling Cython file:

...
        return self._waiting.size

```
cdef _wait (self):
    cdef coro me
    me = the_scheduler._current
    IF CORO_DEBUG:
                ^
```

---

coro/sync.pyx:609:21: Compile-time name 'CORO_DEBUG' not defined
## Error compiling Cython file:

...
# extras used by ironport only

include "ironport.pyx"
include "profile.pyx"
IF UNAME_SYSNAME == "FreeBSD":
    include "aio.pyx"
IF COMPILE_LIO:
##              ^

coro/_coro.pyx:1302:14: Compile-time name 'COMPILE_LIO' not defined
## Error compiling Cython file:

...
    ]

IF UNAME_SYSNAME == "FreeBSD":
    **versions**.append (**aio_version**)

IF COMPILE_LIO:
##              ^

coro/_coro.pyx:1320:14: Compile-time name 'COMPILE_LIO' not defined

building 'coro._coro' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/home/syadasti/shrapnel/. -I/home/syadasti/shrapnel/include -I/usr/include/python2.7 -c coro/_coro.c -o build/temp.linux-x86_64-2.7/coro/_coro.o -Wno-unused-function
coro/_coro.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
error: command 'gcc' failed with exit status 1
syadasti@charlie:~/shrapnel$
